[workspace]

resolver = "2"
members = [
    "keriox_core",
    "keriox_tests",
    "support/gossip",
    "support/teliox",
    "components/witness",
    "components/watcher",
    "components/controller",
    "keriox_sdk",
]

[workspace.package]
repository = "https://github.com/THCLab/keriox"
authors = [
    "Human Colossus Foundation <contact@humancolossus.org>",
]
edition = "2021"
license = "EUPL-1.2"

[workspace.dependencies]
cesrox = { path = "../cesrox/cesr", version = "0.1.4" }
said = { path = "../cesrox/said", version = "0.4.0" }
itertools = "0.11.0"
# fraction = "0.16.0"
fraction = { git = "https://github.com/dnsl48/fraction", rev = "17649f7ff9f0509cfd52fe1ecaa4d97b1cddf851" }

[workspace.metadata.release]

#pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}" ]
#pre-release-commit-message="chore: release {{version}} version"
#publish=false
#shared-version=false
#tag-name="v{{version}}"
tag=false

[workspace.lints.clippy]
result_large_str = "allow"
